services:
  - type: web
    name: blog-app
    env: node
    buildCommand: |
      npm install
      npm install --prefix client
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
